title:             Clean Blog
email:             godteams@naver.com
description:       Tech blog for Game Client Developer
author:            JingonPark
baseurl:           ""
url:               "http://JingonPark.github.io"

# Social Profiles
twitter_username:  Non
github_username:   JingonPark
facebook_username: JingonPark

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
